system/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
| 
*/

Route::group(['middleware' => ['web']], function() {
	
	Route::get('/', 'HomeController@index')->name('home');
	Route::post('/ajax-search', 'HomeController@ajaxSearch')->name('home.ajax-search')->middleware(['xmlhttprequest']);
	Route::get('/search', 'HomeController@search')->name('search');
	Route::get('/post/view/{id}', 'PostController@view')->name('post.view');

	Route::group(['prefix' => 'post/{id}/comments'], function() {
		Route::post('/load', 'PostController@ajaxLoadComment')->name('post.ajax.comments.load')->middleware(['xmlhttprequest']);
		Route::post('/new', 'PostController@ajaxNewComment')->name('post.ajax.comments.new')->middleware(['auth', 'xmlhttprequest']);
		Route::post('/update', 'PostController@ajaxUpdateComment')->name('post.ajax.comments.update')->middleware(['auth', 'xmlhttprequest']);
		Route::post('/delete', 'PostController@ajaxDeleteComment')->name('post.ajax.comments.delete')->middleware(['auth', 'xmlhttprequest']);
	});
	

	Route::get('/page/{slug}', 'PageController@show')->name('page');

	## Auth
	Route::group(['namespace' => 'Auth', 'prefix' => 'auth'], function() {
		Route::get('/login', 'LoginController@showLoginForm')->name('login');
		Route::post('/login', 'LoginController@login')->name('login.proccess');
		Route::get('/logout', 'LoginController@logout')->name('logout');
		Route::get('/register', 'RegisterController@showRegistrationForm')->name('register');
		Route::post('/register', 'RegisterController@register')->name('register.proccess');
		Route::get('/password/reset', 'ForgotPasswordController@showLinkRequestForm')->name('password.request');
		Route::post('/password/email', 'ForgotPasswordController@sendResetLinkEmail')->name('password.email');
		Route::get('/password/reset/{token}', 'ResetPasswordController@showResetForm');
		Route::post('/password/reset', 'ResetPasswordController@reset');
	});


	## Account ##
	Route::group(['middleware' => 'auth', 'namespace' => 'Account', 'prefix' => 'account'], function() {
		Route::get('/activation', 'ActivationController@index')->name('account.activation');
		Route::get('/home', 'HomeController@index')->name('account.home');
		Route::get('/report/new', 'PostController@new')->name('account.newreport');
		Route::post('/report/new', 'PostController@store')->name('account.newreport.store');
		Route::get('/report/edit/{id}', 'PostController@edit')->name('account.report.edit');
		Route::post('/report/edit/{id}', 'PostController@update')->name('account.report.update');
		Route::get('/report/delete/{id}', 'PostController@delete')->name('account.report.delete');
		Route::get('/password', 'ProfileController@changePasswordForm')->name('account.changepassword');
		Route::post('/password', 'ProfileController@changePasswordStore')->name('account.changepassword.store');
		Route::get('/verification', 'VerificationController@form')->name('account.verification');
		Route::post('/verification', 'VerificationController@store')->name('account.verification.store');
		Route::get('/profile', 'ProfileController@index')->name('account.profile');
		Route::post('/profile', 'ProfileController@store')->name('account.profile.store');
	});


	# Admin
	Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'middleware' => ['auth', 'role:admin']], function() {
		Route::get('/', 'HomeController@index')->name('admin.home');
		Route::group(['prefix' => 'posts'], function() {
			Route::get('/', 'PostController@index')->name('admin.posts.index');
			Route::get('/edit/{id}', 'PostController@edit')->name('admin.posts.edit');
			Route::post('/edit/{id}', 'PostController@update')->name('admin.posts.update');
			Route::get('/preview/{id}', 'PostController@preview')->name('admin.posts.preview');
			Route::get('/delete/{id}', 'PostController@delete')->name('admin.posts.delete');
			Route::post('/ajax/search', 'PostController@ajaxSearch')->name('admin.posts.ajax.search');
		});
		Route::group(['prefix' => 'verification'], function() {
			Route::get('/', 'VerificationController@index')->name('admin.verification');
			Route::get('view/{id}', 'VerificationController@show')->name('admin.verification.show');
			Route::post('action/{id}', 'VerificationController@action')->name('admin.verification.action');
		});

		Route::group(['prefix' => 'comment'], function(){
			Route::get('/', 'CommentController@index')->name('comment.index');
			Route::delete('/delete/{comment}', 'CommentController@delete')->name('comment.delete');
		});

		Route::resource('page', 'PageController');

		Route::get('/setting', 'SettingController@setting')->name('setting');
		Route::post('/setting/update', 'SettingController@update')->name('setting.update');
	});


	## Misc
	Route::get('/robots.txt', 'MiscController@robots')->name('robots.txt');
	Route::get('/sitemap.xml', 'MiscController@sitemapIndex')->name('sitemap.xml');

});

system/resources/views/layouts/admin.blade.php
@extends('layouts.app')
@section('main-menu')
              <ul>
                <li class="{{ route('home') == request()->url() ? 'active' : '' }}"><a href="{{ route('home') }}">Beranda</a></li>
                <li class="{{ route('page', 'syarat-ketentuan') == request()->url() ? 'active' : '' }}"><a href="{{ route('page','syarat-ketentuan') }}">Syarat & Ketentuan</a></li>
                <li class="{{ route('page' ,'disclaimer') == request()->url() ? 'active' : '' }}"><a href="{{ route('page','disclaimer') }}">Disclaimer</a></li>
                <li><a href="#">Lainnya <i class="fa fa-caret-down"></i></a>
                  <ul class="dropdown">
                    <li class="{{ route('page','about') == request()->url() ? 'active' : '' }}"><a href="{{ route('page','about') }}"><i class="fa fa-angle-double-right"></i> Tentang Layanan</a></li>
                  </ul>
                </li>
                <li class="{{ route('account.newreport') == request()->url() ? 'active' : '' }}"><a href="{{ route('account.newreport') }}">Kirim Laporan</a></li>
                <li class="btn_item">
                    <ul>
                        <li>
                            <button class="btn_login" onclick="javascript:window.open('{{ route('account.home') }}', '_self');">User Panel</button>
                        </li>
                    </ul>   
                </li>
              </ul>
@endsection
@section('content')
<div id="dashboard_inner_block">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="row">
          <div class="col-md-3 col-sm-4 col-xs-12">
            <div class="dashboard_nav_item hidden-xs hidden-sm">
              <ul>
                <li class="{{ route('account.home') == request()->url() ? 'active' : '' }}"><a href="{{ route('account.home') }}"><i class="fa fa-user"></i> Member Area</a></li>
                <li class="{{ route('admin.home').'/posts' == request()->url() ? 'active' : '' }}"><a href="{{ route('admin.home') }}"><i class="fa fa-tachometer"></i> Dashboard</a></li>
                <li class="{{ route('admin.verification') == request()->url() ? 'active' : '' }}"><a href="{{ route('admin.verification') }}"><i class="fa fa-get-pocket"></i> Verifikasi Member</a></li>
                <li class="{{ route('page.index') == request()->url() ? 'active' : '' }}"><a href="{{ route('page.index') }}"><i class="fa fa-file"></i> Pages</a></li>
                <li class="{{ route('comment.index') == request()->url() ? 'active' : '' }}"><a href="{{ route('comment.index') }}"><i class="fa fa-comments"></i> Comment</a></li>
                <li class="{{ route('setting') == request()->url() ? 'active' : '' }}"><a href="{{ route('setting') }}"><i class="fa fa-gear"></i> Setting</a></li>
                <li><a href="{{ route('logout') }}"><i class="fa fa-sign-out"></i> Keluar</a></li>
              </ul>
            </div>
            <div id="vfx-search-box" class="hidden-md hidden-lg">
              <select id="select-menu" class="form-control">
                <option value="">-- MENU NAVIGASI --</option>
                <option value="{{ route('account.home') }}" {{ route('admin.home') == request()->url() ? 'selected' : '' }}> Dashboard </option>
            </select>
            </div>
          </div>
          <div class="col-md-9 col-sm-8 col-xs-12">
              @if(Session::has('alert-error'))
                <div class="alert alert-danger" role="alert"> {{ Session::get('alert-error') }} </div>
              @elseif(Session::has('alert-success'))
                <div class="alert alert-success" role="alert"> {{ Session::get('alert-success') }} </div>
              @endif
              @yield('admin-content', '')
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
@endsection

system/resources/views/layouts/member.blade.php
@extends('layouts.app')
@section('content')
<div id="dashboard_inner_block">
  <div class="container">
    <div class="row">
      <div class="col-md-12 text-center">
        <div class="row">
          <div class="col-md-3 col-sm-4 col-xs-12">
            <div class="dashboard_nav_item hidden-xs hidden-sm">
              <ul>
                @role('admin')
                <li class="{{ route('admin.home') == request()->url() ? 'active' : '' }}"><a href="{{ route('admin.home') }}"><i class="fa fa-user-secret"></i> Admin Panel</a></li>
                @endrole
                <li class="{{ route('account.home') == request()->url() ? 'active' : '' }}"><a href="{{ route('account.home') }}"><i class="fa fa-tachometer"></i> Dashboard</a></li>
                <li class="{{ route('account.newreport') == request()->url() ? 'active' : '' }}"><a href="{{ route('account.newreport') }}"><i class="fa fa-pencil"></i> Kirim Laporan</a></li>
                <li class="{{ route('account.profile') == request()->url() ? 'active' : '' }}"><a href="{{ route('account.profile') }}"><i class="fa fa-user"></i> Edit Profil</a></li>
                <li class="{{ route('account.verification') == request()->url() ? 'active' : '' }}"><a href="{{ route('account.verification') }}"><i class="fa fa-get-pocket"></i> Verifikasi Akun</a></li>
                <li class="{{ route('account.changepassword') == request()->url() ? 'active' : '' }}"><a href="{{ route('account.changepassword') }}"><i class="fa fa-key"></i> Ubah Kata Sandi</a></li>
                <li><a href="{{ route('logout') }}"><i class="fa fa-sign-out"></i> Keluar</a></li>
              </ul>
            </div>
            <div id="vfx-search-box" class="hidden-md hidden-lg">
              <select id="select-menu" class="form-control">
                <option value="">-- MENU NAVIGASI --</option>
                @role('admin')
                <option value="{{ route('admin.home') }}" {{ route('admin.home') == request()->url() ? 'selected' : '' }}> Admin Panel </option>
                @endrole
                <option value="{{ route('account.home') }}" {{ route('account.home') == request()->url() ? 'selected' : '' }}> Dashboard </option>
                <option value="{{ route('account.newreport') }}" {{ route('account.newreport') == request()->url() ? 'selected' : '' }}> Kirim Laporan </option>
                <option value="{{ route('account.profile') }}" {{ route('account.profile') == request()->url() ? 'selected' : '' }}> Edit Profil </option>
                <option value="{{ route('account.verification') }}" {{ route('account.verification') == request()->url() ? 'selected' : '' }}> Verifikasi Akun </option>
                <option value="{{ route('account.changepassword') }}" {{ route('account.changepassword') == request()->url() ? 'selected' : '' }}> Ubah Kata Sandi </option>
                <option value="{{ route('logout') }}"> Keluar </option>
            </select>
            </div>
          </div>
          <div class="col-md-9 col-sm-8 col-xs-12">
              @if(Session::has('alert-error'))
                <div class="alert alert-danger" role="alert"> {{ Session::get('alert-error') }} </div>
              @elseif(Session::has('alert-success'))
                <div class="alert alert-success" role="alert"> {{ Session::get('alert-success') }} </div>
              @endif
              @yield('member-content', '')
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
@endsection