system/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
| 
*/

Route::group(['middleware' => ['web']], function() {
	
	Route::get('/', 'HomeController@index')->name('home');
	Route::post('/ajax-search', 'HomeController@ajaxSearch')->name('home.ajax-search')->middleware(['xmlhttprequest']);
	Route::get('/search', 'HomeController@search')->name('search');
	Route::get('/post/view/{id}', 'PostController@view')->name('post.view');

	Route::group(['prefix' => 'post/{id}/comments'], function() {
		Route::post('/load', 'PostController@ajaxLoadComment')->name('post.ajax.comments.load')->middleware(['xmlhttprequest']);
		Route::post('/new', 'PostController@ajaxNewComment')->name('post.ajax.comments.new')->middleware(['auth', 'xmlhttprequest']);
		Route::post('/update', 'PostController@ajaxUpdateComment')->name('post.ajax.comments.update')->middleware(['auth', 'xmlhttprequest']);
		Route::post('/delete', 'PostController@ajaxDeleteComment')->name('post.ajax.comments.delete')->middleware(['auth', 'xmlhttprequest']);
	});
	

	Route::get('/page/{slug}', 'PageController@show')->name('page');

	## Auth
	Route::group(['namespace' => 'Auth', 'prefix' => 'auth'], function() {
		Route::get('/login', 'LoginController@showLoginForm')->name('login');
		Route::post('/login', 'LoginController@login')->name('login.proccess');
		Route::get('/logout', 'LoginController@logout')->name('logout');
		Route::get('/register', 'RegisterController@showRegistrationForm')->name('register');
		Route::post('/register', 'RegisterController@register')->name('register.proccess');
		Route::get('/password/reset', 'ForgotPasswordController@showLinkRequestForm')->name('password.request');
		Route::post('/password/email', 'ForgotPasswordController@sendResetLinkEmail')->name('password.email');
		Route::get('/password/reset/{token}', 'ResetPasswordController@showResetForm');
		Route::post('/password/reset', 'ResetPasswordController@reset');
	});


	## Account ##
	Route::group(['middleware' => 'auth', 'namespace' => 'Account', 'prefix' => 'account'], function() {
		Route::get('/activation', 'ActivationController@index')->name('account.activation');
		Route::get('/home', 'HomeController@index')->name('account.home');
		Route::get('/report/new', 'PostController@new')->name('account.newreport');
		Route::post('/report/new', 'PostController@store')->name('account.newreport.store');
		Route::get('/report/edit/{id}', 'PostController@edit')->name('account.report.edit');
		Route::post('/report/edit/{id}', 'PostController@update')->name('account.report.update');
		Route::get('/report/delete/{id}', 'PostController@delete')->name('account.report.delete');
		Route::get('/password', 'ProfileController@changePasswordForm')->name('account.changepassword');
		Route::post('/password', 'ProfileController@changePasswordStore')->name('account.changepassword.store');
		Route::get('/verification', 'VerificationController@form')->name('account.verification');
		Route::post('/verification', 'VerificationController@store')->name('account.verification.store');
		Route::get('/profile', 'ProfileController@index')->name('account.profile');
		Route::post('/profile', 'ProfileController@store')->name('account.profile.store');
	});


	# Admin
	Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'middleware' => ['auth', 'role:admin']], function() {
		Route::get('/', 'HomeController@index')->name('admin.home');
		Route::group(['prefix' => 'posts'], function() {
			Route::get('/', 'PostController@index')->name('admin.posts.index');
			Route::get('/edit/{id}', 'PostController@edit')->name('admin.posts.edit');
			Route::post('/edit/{id}', 'PostController@update')->name('admin.posts.update');
			Route::get('/preview/{id}', 'PostController@preview')->name('admin.posts.preview');
			Route::get('/delete/{id}', 'PostController@delete')->name('admin.posts.delete');
			Route::post('/ajax/search', 'PostController@ajaxSearch')->name('admin.posts.ajax.search');
		});
		Route::group(['prefix' => 'verification'], function() {
			Route::get('/', 'VerificationController@index')->name('admin.verification');
			Route::get('view/{id}', 'VerificationController@show')->name('admin.verification.show');
			Route::post('action/{id}', 'VerificationController@action')->name('admin.verification.action');
		});

		Route::group(['prefix' => 'comment'], function(){
			Route::get('/', 'CommentController@index')->name('comment.index');
			Route::delete('/delete/{comment}', 'CommentController@delete')->name('comment.delete');
		});

		Route::resource('page', 'PageController');

		Route::get('/setting', 'SettingController@setting')->name('setting');
		Route::post('/setting/update', 'SettingController@update')->name('setting.update');
	});


	## Misc
	Route::get('/robots.txt', 'MiscController@robots')->name('robots.txt');
	Route::get('/sitemap.xml', 'MiscController@sitemapIndex')->name('sitemap.xml');

});

system/resources/views/admin/pages/create.blade.php
@extends('layouts.admin')
@section('title', 'Buat Halaman')
@section('css')
<style type="text/css">
	.screenshot { padding: 10px; max-height: 150px }
	.img-ss { min-height: 180px; }
</style>
@endsection
@section('admin-content')
<form action="{{ route('page.store') }}" method="POST" enctype="multipart/form-data" id="new-post-form">
	@csrf
            <div class="submit_listing_box">
              <h3>Buat Halaman</h3>
              <div class="form-alt" style="margin-bottom: 20px">
                <div class="row">
                  <div class="form-group col-md-12 col-sm-12 col-xs-12">
                    <label style="font-size:16px;font-weight:500">Judul Halaman :*</label>
                    <input placeholder="(wajib)" class="form-control" type="text" value="{{ old('title')}}" name="title" required="">
                    @if ($errors->has('title'))
						<div class="form-error-message"><i class="glyphicon glyphicon-remove-circle"></i> {{ $errors->first('title') }}</div>
					@endif
                  </div>
                </div>
              </div>
              <div class="form-alt">
              	<div class="row">
              		<div class="col-md-12 col-sm-12 col-xs-12"><label style="font-size:16px;font-weight:500">Konten (min. 300 karakter) :*</label></div>
	                <div class="form-group col-md-12 col-sm-12 col-xs-12">
	                  	<textarea placeholder="(wajib)" class="form-control" rows="5" name="content">{!! old('content')!!}</textarea>
	                  	@if ($errors->has('content'))
						<div class="form-error-message"><i class="glyphicon glyphicon-remove-circle"></i> {{ $errors->first('content') }}</div>
					@endif
	                </div>
	                <div class="clearfix"></div>
	            </div>
              </div>
              <div class="form-alt" style="margin-bottom: 20px">
                <div class="row">
                  <div class="form-group col-md-12 col-sm-12 col-xs-12">
                    <label style="font-size:16px;font-weight:500">Status :*</label>
                    <select name="status" class="form-control" required="">
                    	<option value="1">Aktif</option>
                    	<option value="0">Non Aktif</option>
                    </select>
                    @if ($errors->has('title'))
						<div class="form-error-message"><i class="glyphicon glyphicon-remove-circle"></i> {{ $errors->first('title') }}</div>
					@endif
                  </div>
                </div>
              </div>
                <div class="from-list-lt">
	              <div class="form-group">
	                <button class="btn" type="submit">Simpan</button>
	              </div>
	            </div>
            </div>
</form>
@endsection

@section('js')
<script src="{{ asset('/assets/vendor/wysiwyg/js/tinymce.min.js') }}"></script>
<script type="text/javascript">
	$(document).ready(function() {
      tinymce.init({
          selector: 'textarea[name=content]',
          height: 200,
          theme: 'modern',
          plugins: [
              'advlist autolink lists link image charmap print preview hr anchor pagebreak',
              'searchreplace wordcount visualblocks visualchars code fullscreen',
              'insertdatetime media nonbreaking save table contextmenu directionality',
              'emoticons template paste textcolor colorpicker textpattern imagetools codesample toc'
          ],
          toolbar1: 'undo redo | insert | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image',
          toolbar2: 'print preview media | forecolor backcolor emoticons | codesample',
          image_advtab: true
      });
 });
</script>
@endsection

system/resources/views/admin/pages/edit.blade.php
@extends('layouts.admin')
@section('title', 'Edit Halaman')
@section('css')
<style type="text/css">
	.screenshot { padding: 10px; max-height: 150px }
	.img-ss { min-height: 180px; }
</style>
@endsection
@section('admin-content')
<form action="{{ route('page.update' ,$page) }}" method="POST" enctype="multipart/form-data" id="new-post-form">
	@csrf
  @method('PATCH')
            <div class="submit_listing_box">
              <h3>Edit Halaman</h3>
              <div class="form-alt" style="margin-bottom: 20px">
                <div class="row">
                  <div class="form-group col-md-12 col-sm-12 col-xs-12">
                    <label style="font-size:16px;font-weight:500">Judul Halaman :*</label>
                    <input placeholder="(wajib)" class="form-control" type="text" value="{{ old('title') ?? $page->title}}" name="title" required="">
                    @if ($errors->has('title'))
						<div class="form-error-message"><i class="glyphicon glyphicon-remove-circle"></i> {{ $errors->first('title') }}</div>
					@endif
                  </div>
                </div>
              </div>
              <div class="form-alt">
              	<div class="row">
              		<div class="col-md-12 col-sm-12 col-xs-12"><label style="font-size:16px;font-weight:500">Konten (min. 300 karakter) :*</label></div>
	                <div class="form-group col-md-12 col-sm-12 col-xs-12">
	                  	<textarea placeholder="(wajib)" class="form-control" rows="5" name="content">{!! old('content')  ?? $page->content !!}</textarea>
	                  	@if ($errors->has('content'))
						<div class="form-error-message"><i class="glyphicon glyphicon-remove-circle"></i> {{ $errors->first('content') }}</div>
					@endif
	                </div>
	                <div class="clearfix"></div>
	            </div>
              </div>
              <div class="form-alt" style="margin-bottom: 20px">
                <div class="row">
                  <div class="form-group col-md-12 col-sm-12 col-xs-12">
                    <label style="font-size:16px;font-weight:500">Status :*</label>
                    <select name="status" class="form-control" required="">
                    	<option value="1">Aktif</option>
                    	<option value="0" {{ $page->status == 0 ? 'selected' : ''}}>Non Aktif</option>
                    </select>
                    @if ($errors->has('status'))
						<div class="form-error-message"><i class="glyphicon glyphicon-remove-circle"></i> {{ $errors->first('status') }}</div>
					@endif
                  </div>
                </div>
              </div>
                <div class="from-list-lt">
	              <div class="form-group">
	                <button class="btn" type="submit">Simpan</button>
	              </div>
	            </div>
            </div>
</form>
@endsection

@section('js')
<script src="{{ asset('/assets/vendor/wysiwyg/js/tinymce.min.js') }}"></script>
<script type="text/javascript">
	$(document).ready(function() {
      tinymce.init({
          selector: 'textarea[name=content]',
          height: 200,
          theme: 'modern',
          plugins: [
              'advlist autolink lists link image charmap print preview hr anchor pagebreak',
              'searchreplace wordcount visualblocks visualchars code fullscreen',
              'insertdatetime media nonbreaking save table contextmenu directionality',
              'emoticons template paste textcolor colorpicker textpattern imagetools codesample toc'
          ],
          toolbar1: 'undo redo | insert | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image',
          toolbar2: 'print preview media | forecolor backcolor emoticons | codesample',
          image_advtab: true
      });
 });
</script>
@endsection

system/resources/views/admin/pages/index.blade.php
@extends('layouts.admin')
@section('title', 'Halaman | Admin')
@section('css')
<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
@endsection
@section('admin-content')
<div class="">
	<a href="{{ route('page.create') }}" class="btn btn-primary">Tambah Halaman</a>
	<table class="table table-hover table-stripped table-bordered" style="margin-top: 7px">
		<thead>
			<tr style="background: #0CB4FF;color:#fff">
				<th style="width:90px">ID</th>
				<th>Title</th>
				<th class="text-center" style="width:90px">Status</th>
				<th class="text-center" style="width:120px">Tindakan</th>
			</tr>
		</thead>
		<tbody id="report-table-body">
			@if(count($pages) > 0)
				@foreach($pages as $page)
				<tr class="data-child">
					<td class="text-center"><b>{{ $page->id }}</b></td>
					<td>
						{{ $page->title }}
					</td>
					<td class=" text-center">
						@switch($page->status)
							@case(1)
								<span class="label label-success">Active</span>
								@break;
							@case(0)
								<span class="label label-danger">Nonactive</span>
								@break;
							@default
								@break
						@endswitch
					</td>
					<td class=" text-center">
						<a href="{{ route('page.show', $page) }}">
						  <span class="label label-info"><i class="fa fa-eye"></i></span>
						</a>
						<a href="{{ route('page.edit', $page) }}">
						  <span class="label label-warning"><i class="fa fa-pencil"></i></span>
						</a>
						<button class="btn btn-xs btn-danger" href="{{ route('page.destroy', $page) }}" id="delete" data-title="{{$page->title}}">
						  <i class="fa fa-trash-o"></i>
						</button>
					</td>
				</tr>
				@endforeach
			@else
				<tr>
					<td colspan="5">Belum ada data</td>
				</tr>
			@endif
		</tbody>
	</table>
</div>

                <form action="" method="POST" id="deleteForm">
                    @csrf
                    @method('DELETE')
                    <input type="submit" style="display: none;">
                </form>
@endsection

@section('js')
<script type="text/javascript">
    $('button#delete').on('click', function(){
        var href = $(this).attr('href');
        var title = $(this).data('title');
        swal({
          title: "Anda yakin akan menghapus halaman "+ title +" ?",
          text: "Setelah dihapus halaman tidak dapat dikembalikan",
          icon: "warning",
          buttons: true,
          dangerMode: true,
        })
        .then((willDelete) => {
          if (willDelete) {
            $('#deleteForm').attr('action', href);
            $('#deleteForm').submit();
          }
        });
    });
</script>
@endsection

system/resources/views/admin/pages/show.blade.php
@extends('layouts.app')
@section('title', $page->title)
@section('css')
<link rel="stylesheet" href="{{ asset('/assets/css/superlist.css') }}" type="text/css">
<link rel="stylesheet" href="{{ asset('/assets/js/owl.carousel/owl.carousel.css') }}" type="text/css">
<link rel="stylesheet" href="{{ asset('/assets/js/colorbox/example1/colorbox.css') }}" type="text/css">
@endsection
@section('content')
<div class="details-lt-block">
  <div class="container header_slt_block">
    <div class="slt_item_head">
    </div>
  </div>
</div>
<div id="vfx-product-inner-item">
  <div class="container">
    <div class="row">
      <div class="col-md-9 col-sm-8 col-xs-12">
        <h3>{{$page->title}}</h3>
        {!! html_entity_decode($page->content) !!}
      </div>
      <div class="col-md-3 col-sm-4 col-xs-12">
          
      </div>
    </div>
  </div>
</div>
@endsection

@section('js')
<script src="{{ asset('/assets/js/colorbox/jquery.colorbox-min.js') }}"></script> 
<script src="{{ asset('/assets/js/bootstrap-select/bootstrap-select.min.js') }}"></script> 
<script src="{{ asset('/assets/js/owl.carousel/owl.carousel.js') }}"></script> 
<script src="{{ asset('/assets/js/superlist.js') }}"></script>
@endsection